config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :feedback_reviews
    resources :reviews do
      member do
        get :approve
      end
      resources :feedback_reviews
    end
    resource :review_settings
  end

  resources :products do
    resources :reviews do
      collection do
        get :terms
        get "submissionguidelines"
      end
    end
  end
  match "/reviews/:review_id/feedback(.:format)" => "feedback_reviews#create", :via => :post, :as => "feedback_review"
end

app/models/feedback_review.rb
class FeedbackReview < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  validates_presence_of :review_id
  validates_numericality_of :rating, :only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5, :message => I18n.t('you_must_enter_value_for_rating')

  default_scope order("feedback_reviews.created_at DESC")

end

app/models/product_decorator.rb
# Add access to reviews/ratings to the product model
Product.class_eval do
  has_one :rating
  has_many :reviews

  def get_stars
    if rating.nil?
      [0,0]
    else
      [rating.get_stars, rating.count]
    end
  end

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :product

  NB_STARS=5
  def self.get_nb_stars
    NB_STARS
  end

  def add_rating(n)
    self.value = value * count + n
    self.count = count + 1
    self.value = value / count
    save
  end
  
  def get_stars
    (self.value ? self.value : 0 + 0.5).floor
  end
  
end

app/models/review.rb
# -*- coding: utf-8 -*-
require 'sanitize'
class Review < ActiveRecord::Base
  belongs_to :product
  has_many   :feedback_reviews

  include Rakismet::Model
  rakismet_attrs :author => :name,
  :content => :review,
  :author_email => :email

  validates_presence_of :name
  validates :review, :presence => true, :uniqueness => true, :length => { :minimum => 50 }
  validates_numericality_of :rating, :only_integer => true, :message => I18n::t('you_need_to_rate_your_review')

  default_scope order("reviews.created_at DESC")
  scope :approved,  where("approved = ?", true)
  scope :not_approved, where("approved = ?", false)

  scope :approval_filter, lambda {|*args| {:conditions => ["(? = ?) or (approved = ?)", Spree::Reviews::Config[:include_unapproved_reviews], true, true ]}}

  scope :oldest_first, :order => "created_at asc"
  scope :preview,      :limit => Spree::Reviews::Config[:preview_size], :order=>"created_at desc"

  def feedback_stars
    return 0 if feedback_reviews.count <= 0
    ((feedback_reviews.sum(:rating)/feedback_reviews.count) + 0.5).floor
  end

  def before_save 
    self.review = Sanitize.clean(self.review, Sanitize::Config::RESTRICTED)
  end 


  private
  def allow_some_html(s) 
    # converting newlines 
    s.gsub!(/\r\n?/, "\n") 
    
    # escaping HTML to entities 
    s = s.to_s.gsub('&', '&amp;').gsub('<', '&lt;').gsub('>', '&gt;') 
    
    # blockquote tag support 
    s.gsub!(/\n?&lt;blockquote&gt;\n*(.+?)\n*&lt;\/blockquote&gt;/im, "<blockquote>\\1</blockquote>") 
    
    # other tags: b, i, em, strong, u 
    %w(b i em strong u).each { |x|
      s.gsub!(Regexp.new('&lt;(' + x + ')&gt;(.+?)&lt;/('+x+')&gt;',
                         Regexp::MULTILINE|Regexp::IGNORECASE), 
              "<\\1>\\2</\\1>") 
    } 
    
    # A tag support 
    # href="" attribute auto-adds http:// 
    s = s.gsub(/&lt;a.+?href\s*=\s*['"](.+?)["'].*?&gt;(.+?)&lt;\/a&gt;/im) { |x|
      '<a href="' + ($1.index('://') ? $1 : 'http://'+$1) + "\">" + $2 + "</a>" 
    } 
    
    # replacing newlines to <br> ans <p> tags 
    # wrapping text into paragraph 
    s = "<p>" + s.gsub(/\n\n+/, "</p>\n\n<p>").
      gsub(/([^\n]\n)(?=[^\n])/, '\1<br />') + "</p>" 
    
    s      
  end 

end

app/models/reviews_configuration.rb
class ReviewsConfiguration < Configuration
  # include non-approved reviews in (public) listings 
  preference :include_unapproved_reviews, :boolean, :default => 'false'

  # control how many reviews are shown in summaries etc.
  preference :preview_size, :integer, :default => 3
end

app/controllers/admin/feedback_reviews_controller.rb
class Admin::FeedbackReviewsController <  Admin::BaseController
  resource_controller
  belongs_to :review

  create.response do |wants|
    wants.html { redirect_to collection_path }
  end

  update.response do |wants|
    wants.html { redirect_to collection_path }
  end

  destroy.response do |wants|
    wants.html { redirect_to collection_path }
  end
end

app/controllers/admin/review_settings_controller.rb
class Admin::ReviewSettingsController < Admin::BaseController
  def update
    # workaround for unset checkbox behaviour
    params[:preferences][:include_unapproved_reviews] = false if params[:preferences][:include_unapproved_reviews].blank?
    Spree::Reviews::Config.set(params[:preferences])

    respond_to do |format|
      format.html {
        redirect_to admin_review_settings_path
      }
    end
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::BaseController
   
  layout 'admin'

  resource_controller

  index.before do 
    @unapproved_reviews = Review.not_approved.find(:all, :order => "created_at DESC")
    @approved_reviews   = Review.approved.find(:all, :order => "created_at DESC")
  end

  create.response do |wants|
    wants.html { redirect_to admin_reviews_path }
  end

  update.response do |wants|
    wants.html { redirect_to admin_reviews_path }
  end

  def approve
    r = Review.find(params[:id])

    r.approved = true
    if r.product.rating.nil? 
      r.product.rating = Rating.create :value => 0, :count => 0
    end
    r.product.rating.add_rating(r.rating)

    if r.save
       flash[:notice] = t("info_approve_review")
    else
       flash[:error] = t("error_approve_review")
    end
    redirect_to admin_reviews_path
  end
end

app/controllers/feedback_reviews_controller.rb
class FeedbackReviewsController < Spree::BaseController
  helper Spree::BaseHelper
  def create
    params[:feedback_review][:rating].sub!(/\s*stars/,'') unless params[:feedback_review][:rating].blank?

    @review = Review.find_by_id(params[:review_id])
    @review &&
      (@feedback_review = @review.feedback_reviews.new(params[:feedback_review])) && @feedback_review.save

    respond_to do |format|
      format.html { redirect_to :back  }
      format.js   { render :action => :create }
    end

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < Spree::BaseController
  helper Spree::BaseHelper

  def index
    @product = Product.find_by_permalink params[:product_id]
    @approved_reviews = Review.approved.find_all_by_product_id(@product.id) 
  end

  def new
    @product = Product.find_by_permalink params[:product_id] 
    @review = Review.new :product => @product
    @name = (current_user and not current_user.orders.blank? and current_user.orders.last.ship_address) ? current_user.orders.last.ship_address.firstname : '' 
  end

  # save if all ok
  def create
    @product = Product.find_by_permalink params[:product_id]
    params[:review][:rating].sub!(/\s*stars/,'') unless params[:review][:rating].blank?

    @review = Review.new :product => @product
    if @review.update_attributes(params[:review]) 
      if @review.spam?
        flash[:error] = t('you_review_is_spam')
        redirect_to (product_path(@product))
      else
        flash[:notice] = t('review_successfully_submitted')
        redirect_to (product_path(@product))
      end
    else
      # flash[:notice] = 'There was a problem in the submitted review'
      render :action => "new" 
    end
  end
  def terms
  end
end

app/helpers/admin/feedback_reviews_helper.rb
module Admin::FeedbackReviewsHelper
end

app/helpers/feedback_reviews_helper.rb
module FeedbackReviewsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star(the_class) 
    "<span class=\"#{the_class}\"> &#10030; </span>"
  end

  def mk_stars(m)
    (1..5).collect {|n| n <= m ? star("lit") : star("unlit") }.join
  end
  
  def txt_stars(n, show_out_of = true)
    res = I18n.t('star', :count => n)
    res += ' ' + t('out_of_5') if show_out_of
    res
  end

end

app/views/admin/feedback_reviews/index.html.erb
<% render 'admin/shared/product_sub_menu' %>
<h1><%= link_to t('feedback_review_for', :review => @review.title ), admin_reviews_path %></h1>


<table class="index">
  <tr>
    <th><%= t('date_') %></th>
    <th><%= t('user') %></th>
    <th><%= t('stars') %></th>
    <th></th>
  </tr>
  <% collection.each do |feedback| %>
    <tr id="<%= dom_id(feedback) %>">
      <td><%= l feedback.created_at %></td>
      <td><%= feedback.user.try(:login) || "anonymus" %></td>
      <td><%= feedback.rating %></td>
      <td class="actions">
        <%= link_to_delete feedback  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/review_settings/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("reviews.review_settings") %></h1>

<% form_tag(admin_review_settings_path, :method => :put) do -%>
  <p>
    <label><%= t("reviews.include_unapproved") %>:</label>
    <%= check_box_tag('preferences[include_unapproved_reviews]', "1", Spree::Reviews::Config[:include_unapproved_reviews]) %>
  </p>
  <p>
    <label><%= t('reviews.preview_size') %>:</label>
    <%= text_field_tag('preferences[preview_size]', Spree::Reviews::Config[:preview_size], :size => 3) %>
  </p>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_review_settings_url %>
  </p>
<% end -%>

app/views/admin/review_settings/show.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("reviews.review_settings") %></h1>

<table>
  <tr>
    <th scope="row"><%= t("reviews.include_unapproved") %>:</th>
    <td><%= Spree::Reviews::Config[:include_unapproved_reviews] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("reviews.preview_size") %>:</th>
    <td><%=  Spree::Reviews::Config[:preview_size] %></td>
  </tr>
</table>

<p>
  <%= link_to_with_icon('edit', t("edit"), edit_admin_review_settings_path) %>
</p>

app/views/admin/reviews/_form.html.erb
<%= render "shared/error_messages", :target => @review %>
<br />
<p>
  <%= form.text_field :name, :size => 30 %>
</p>
<p>
  <%= form.text_area :review, :cols => 60, :rows => 10 %>
</p>
<br/>
<p>
  <%= form.submit button_name %>
</p>

app/views/admin/reviews/edit.html.erb
<% render 'admin/shared/product_sub_menu' %>
<h1>Editing review for <%= link_to @review.product.name, product_path(@review.product) %></h1>

<h2>Original version</h2>

<p>
<%= @review.review %>
</p>
<br/>

<h2>Edited version</h2>

<% form_for([:admin, @review]) do |f| %>
  <%= render :partial => f,
             :locals  => { :button_name => "Update" } %>
<% end %>

<%= link_to t('back_reviews'), admin_reviews_path %>

app/views/admin/reviews/index.html.erb
<% render 'admin/shared/product_sub_menu' %>
<h1><%= t('review_management_description') %></h1>

<% for reviews in [["Unapproved", @unapproved_reviews], ["Approved", @approved_reviews]] %>
  <h2><%= t(reviews[0]+"_reviews") %></h2>

  <table cellspacing=6 class="index">
    <tr>
      <th><%= t('date_') %></th>
      <th><%= t('user') %></th>
      <th><%= t('review_title') %> / <%= t('product') %></th>
      <th><%= t('review_content') %></th>
      <th></th>
    </tr>

    <% for review in reviews[1] %>
    <tr>
      <td>
        <%= l review.created_at %>
      </td>
      <td>
        <%= review.name %><%= t('from') %> <%= review.location %>
      </td>
      <td>
        <%= h review.title %>
        <br/>
        <%= t('for') %> <%= link_to review.product.name, product_path(review.product) %>
      </td>
      <td style="border: 1px dashed green" width="60%">
        <br/>
        <%= h review.review %>
      </td>
      <td>
        <% unless review.approved %>
          <%= link_to t('approve'), {:action => 'approve', :id => review.id} %> <br />
        <% end %>
        <%= link_to t('feedback'), admin_review_feedback_reviews_path(review) %>(<%= review.feedback_stars %>/<%= review.feedback_reviews.count %>) <br/>
        <%= link_to t('edit'), [:edit, :admin, review] %> <br/>
        <%= link_to t('destroy'), [:admin, review], :method => :delete, :confirm => t('are_you_sure_review') %>

      </td>
    </tr>
  <% end %>
  </table>
  <br/>
<% end %>

app/views/feedback_reviews/_form.html.erb
<%= render :partial => "feedback_reviews/summary", :locals => {:review => review}%>
<%= form_for((@feedback_review ||= review.feedback_reviews.build), :url => feedback_review_path(review), :method => :post, :remote => true) do |f| %>
<% unless @feedback_review.errors.empty? %>
 <span class="error"><%= @feedback_review.errors[:rating] %></span>
 <br />
<% end %>

<%= t(:was_this_review_helpful) %>
<% for i in 1..Rating.get_nb_stars %>
<%= radio_button_tag "feedback_review[rating]", pluralize(i, 'stars'), false, :class => "star" %>
<% end %>
<%= hidden_field_tag "feedback_review[user_id]", current_user.try(:id) %>
<button class="feedback-review"><span><%= t("yes") %></span></button>
<% end %>

app/views/feedback_reviews/_summary.html.erb
<p>
  <%= t('voice', :count => review.feedback_reviews.count) %>.
  <span title="<%=pluralize(review.feedback_stars, 'star')%> out of 5">
  <%= render :partial => "reviews/stars", :locals => {:stars => review.feedback_stars} %>
  </span> &nbsp;
</p>

app/views/feedback_reviews/create.js.erb
<% if @feedback_review.valid? %>
$("div#feedback_review_<%= @review.id %>").html("<%= escape_javascript(render(:partial => "feedback_reviews/summary", :locals => {:review => @review})) %>");
<% else %>
$("div#feedback_review_<%= @review.id %>").html("<%= escape_javascript(render(:partial => "feedback_reviews/form", :locals => {:review => @review})) %>");

<% end %>
$(document).ready(function(){$("div#feedback_review_<%= @review.id %>").find(".star").rating({required:true});});

app/views/reviews/_fine_print.html.erb
<br/>
<h2><%= t('the_fine_print') %></h2>
<ul>
    <li><%= t('terms_text') %>: <%= link_to t("terms and conditions"), url_for(:action => 'terms') %></li>
    <li><%= t('approved_text') %></li>
    <li><%= t('guideline_text') %>: <%= link_to t("review guidelines"), url_for(:action => 'submissionguidelines') %></li>
</ul>

app/views/reviews/_stars.html.erb
<% if defined? edit_enabled 
    state = "" 
    name  = "review[rating]" 
  else  
    state = 'disabled="disabled"' 
    name  = defined?(review).nil? ? Time.now.tv_usec.to_s : "review_#{review}" 
  end %>
<% for i in 1..Rating.get_nb_stars %>
  <input name="<%= name %>" 
         type="radio" class="star" 
         value="<%= pluralize(i, 'stars') %>" <%= state %> 
         <%= "checked=\"checked\"" if i==stars  %> />
<% end %>

app/views/reviews/_stars0.html.erb
<span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span>

app/views/reviews/_stars1.html.erb
<span class="lit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span>

app/views/reviews/_stars2.html.erb
<span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span>

app/views/reviews/_stars3.html.erb
<span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="unlit"> &#10030; </span><span class="unlit"> &#10030; </span>

app/views/reviews/_stars4.html.erb
<span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="unlit"> &#10030; </span>

app/views/reviews/_stars5.html.erb
<span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="lit"> &#10030; </span><span class="lit"> &#10030;</span>

app/views/reviews/index.html.erb
<%= render :partial => 'shared/reviews' %>

app/views/reviews/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag :ckeditor %>
<% end %>
<!-- <h1>Product review submission</h1> -->

<h2> <%= I18n.t('leave_us_a_review_for') + ' "' + @product.name + '"' %> </h2>

<%= form_for @review, :url => {:action => 'create'} do |f| %>
<%= render "shared/error_messages", :target => @review %>
<%= f.hidden_field :product_id, :value => @product.id %>

<table cellspacing="0" cellpadding="2">
  <tbody>
    <tr valign="top">
      <td class="fieldtitle right nowrap">
	<%= f.label :name, "<strong>#{ I18n.t('reviews.your_name')}</strong>".html_safe %>
      </td>
      <td width="100%">
	<%= f.text_field :name, :size => 50, :maxlength => 100, :class => 'required', :value => (params[:review][:name] if params[:review]) || @name %><span class="req">*</span>
      </td>
    </tr>
    <tr valign="top">
      <td class="fieldtitle right nowrap">
	<%= f.label :email, "<strong>#{ I18n.t('reviews.your_email')}</strong>".html_safe %>
      </td>
      <td width="100%">
	<%= f.text_field :email, :size => 50, :maxlength => 100, :class => 'required', :value => (params[:review][:email] if params[:review]) || @email %><span class="req">*</span>
      </td>
    </tr>
    <tr valign="top">
      <td style="padding-top: 5px; padding-bottom: 5px;" class="fieldtitle right nowrap">
    	<strong><%= I18n.t('rating') %></strong>
      </td>
      <td style="padding-top: 5px; padding-bottom: 5px;">
        <span class="req">*</span><%= render :partial => "reviews/stars", :locals => {:stars => @review.rating, :edit_enabled => true} %>
      </td>
    </tr>
    <tr valign="top">
      <td class="fieldtitle right nowrap">
    	<%= f.label :title, raw("<strong>#{ I18n.t('review_title')}</strong>") %>
      </td>
      <td>
        <%= f.text_field :title, :maxlength => "255", :size => "50", :class => 'required' %>
      </td>
    </tr>
    <tr valign="top">
      <td class="fieldtitle right nowrap">
    	<%= f.label :review, raw("<strong>#{ I18n.t('review_content')}</strong>") %>
      </td>
      <td>
	<span class="req">*</span>
    	<%= f.cktext_area :review, :toolbar=>'Basic', :wrap => "virtual", :rows => "10", :cols => "50" %>
      </td>
    </tr>
    <tr>
      <td> </td>
      <td style="padding-top: 5px;">
    	<%= f.submit I18n.t('submit_your_review'), :class => "button bg_darkfirst".html_safe %>
      </td>
    </tr>
  </tbody></table>
<% end %>

<%= render :partial => "fine_print" %>

app/views/reviews/submissionguidelines.html.erb
<h2> <%= t('submission_guidelines') %> </h2>

<p>
Dummy document - expected to be over-ridden in specific instantiations
</p>

app/views/reviews/terms.html.erb
<h2> <%= t('terms_and_conditions') %> </h2>

<p>
Dummy document - expected to be over-ridden in specific instantiations
</p>

app/views/shared/_rating.html.erb
<% stars = product.get_stars %>
<div class="header clear">
  <% unless stars[1].nil? or stars[1] == 0 -%>
    <%= t 'average_customer_rating' %>: 
    <br/>
    <span title="<%= txt_stars(stars[0]) %>">
      <%= render :partial => "reviews/stars", :locals => {:stars => stars[0]} %>
    </span> &nbsp;
    <br/>
    (<%= t('based_upon') %> <%= t('review', :count => stars[1]) %>)
    <br/>
    <br/>
  <% end %>
</div>

app/views/shared/_review.html.erb
<div class="review">
  <span title="<%= txt_stars(review.rating) %>">
    <%= render :partial => "reviews/stars", :locals => {:stars => review.rating} %>
  </span>
  &nbsp; <span class="title"><%= review.title %> </span>
  <br/>
  <em><span class="attribution"><%= "<strong>#{review.name}</strong> - ".html_safe if review.name%><noindex><%= t('submitted_on') %> <%= l review.created_at.to_date %></noindex></span></em>
  <p>
  <%= review.review.html_safe %>
  </p>
  <div id="feedback_review_<%= review.id %>">
    <%= render :partial => "feedback_reviews/form", :locals => {:review => review} %>
  </div>
</div>

app/views/shared/_review_summary.html.erb
<%# provisional snapshot of review info %>
<div id="reviews">
  <%= render :partial => 'shared/rating', :locals => {:product => @product, :review => 0} %>
  <% for review in @product.reviews.approval_filter.preview %>
    <%= render :partial => 'shared/review', :locals => {:review => review} %>
  <% end %>

  <%= link_to t('write_your_own_review'), new_product_review_path(@product), :class => "button" %>
</div>

app/views/shared/_reviews.html.erb
<div id="reviews">
  <%= render :partial => 'shared/rating', :locals => {:product => @product} %>
  <% for review in @product.reviews.approval_filter %>
    <%= render :partial => 'shared/review', :locals => {:review => review} %>
  <% end %>

  <%= link_to t('write_your_own_review'), new_product_review_path(@product), :class => "button" %>
</div>

app/views/shared/_shortrating.html.erb
<% stars = product.get_stars %>
<span style="float:left;" title="<%= txt_stars(stars[0]) %>">
  <%= render :partial => "reviews/stars", :locals => {:stars => stars[0]} %>
</span>
<span style="float:right;">
  <%= t('review', :count => stars[1]) %>
</span>
<br/>